# Generated by Django 6.0.3 on 2026-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenciones', '0002_horariomantencion_mantencion_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('ingresada', 'Ingresada'), ('aceptada', 'Aceptada'), ('en_revision', 'En revision'), ('en_proceso', 'En proceso'), ('esperando_repuestos', 'Esperando repuestos'), ('finalizada', 'Finalizada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='ingresada', max_length=24, verbose_name='estado'),
        ),
    ]
