# Generated by Django 6.0.3 on 2026-03-19 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenciones', '0003_alter_mantencion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MantencionEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=24, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('ingresada', 'Ingresada'), ('aceptada', 'Aceptada'), ('en_revision', 'En revision'), ('en_proceso', 'En proceso'), ('esperando_repuestos', 'Esperando repuestos'), ('finalizada', 'Finalizada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistio')], max_length=24, verbose_name='estado nuevo')),
                ('fuente', models.CharField(choices=[('portal_cliente', 'Portal cliente'), ('admin_panel', 'Admin panel'), ('api', 'API')], default='api', max_length=24, verbose_name='fuente')),
                ('observacion', models.CharField(blank=True, default='', max_length=255, verbose_name='observacion')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de cambio')),
            ],
            options={
                'verbose_name': 'historial de estado de mantencion',
                'verbose_name_plural': 'historial de estados de mantenciones',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='estado',
            field=models.CharField(choices=[('ingresada', 'Ingresada'), ('aceptada', 'Aceptada'), ('en_revision', 'En revision'), ('en_proceso', 'En proceso'), ('esperando_repuestos', 'Esperando repuestos'), ('finalizada', 'Finalizada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistio')], default='ingresada', max_length=24, verbose_name='estado'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['created_at'], name='idx_mantencion_created_at'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['fecha_ingreso'], name='idx_mantencion_fecha_ingreso'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['estado'], name='idx_mantencion_estado'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['tipo_mantencion'], name='idx_mantencion_tipo'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['fecha_ingreso', 'hora_ingreso'], name='idx_mantencion_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='mantencion',
            index=models.Index(fields=['created_at', 'estado'], name='idx_mantencion_created_estado'),
        ),
        migrations.AddField(
            model_name='mantencionestadohistorial',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenciones_estado_cambios', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='mantencionestadohistorial',
            name='mantencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='mantenciones.mantencion', verbose_name='mantencion'),
        ),
        migrations.AddIndex(
            model_name='mantencionestadohistorial',
            index=models.Index(fields=['changed_at'], name='idx_hist_mant_changed_at'),
        ),
        migrations.AddIndex(
            model_name='mantencionestadohistorial',
            index=models.Index(fields=['estado_nuevo'], name='idx_hist_mant_estado_nuevo'),
        ),
        migrations.AddIndex(
            model_name='mantencionestadohistorial',
            index=models.Index(fields=['mantencion', 'changed_at'], name='idx_hist_mant_mant_fecha'),
        ),
    ]
