# Generated by Django 6.0.3 on 2026-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenciones', '0013_protect_changed_by_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantencion',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, verbose_name='motivo de cancelacion'),
        ),
    ]
