import {
  createAccesorioMoto,
  createAccesorioRider,
  createCategoriaAccesoriosMotos,
  createCategoriaAccesoriosRider,
  deleteCategoriaAccesoriosMotos,
  deleteCategoriaAccesoriosRider,
  getAccesoriosMotosAdmin,
  getAccesoriosMotosMeta,
  getAccesoriosRiderAdmin,
  getAccesoriosRiderMeta,
  getCategoriasAccesoriosMotosAdmin,
  getCategoriasAccesoriosRiderAdmin,
  getCategoriasProducto,
  getProductos,
  updateProductoAdmin,
  deleteProductoAdmin,
  updateCategoriaAccesoriosMotos,
  updateCategoriaAccesoriosRider,
} from "../../../services/productosService";

export {
  createAccesorioMoto,
  createAccesorioRider,
  createCategoriaAccesoriosMotos,
  createCategoriaAccesoriosRider,
  deleteCategoriaAccesoriosMotos,
  deleteCategoriaAccesoriosRider,
  getAccesoriosMotosAdmin,
  getAccesoriosMotosMeta,
  getAccesoriosRiderAdmin,
  getAccesoriosRiderMeta,
  getCategoriasAccesoriosMotosAdmin,
  getCategoriasAccesoriosRiderAdmin,
  getCategoriasProducto,
  getProductos,
  updateProductoAdmin,
  deleteProductoAdmin,
  updateCategoriaAccesoriosMotos,
  updateCategoriaAccesoriosRider,
};
