# Generated by Django 6.0.3 on 2026-03-14 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cilindrada', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('es_destacada', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoriamoto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.marca')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/galeria/')),
                ('texto_alternativo', models.CharField(blank=True, max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='motos.moto')),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='motos.moto')),
            ],
        ),
    ]
