# Generated by Django 6.0.3 on 2026-03-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0004_refactor_modelo_tecnico_moto_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_ficha', to='motos.moto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('valor', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='motos.seccionfichatecnica')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='seccionfichatecnica',
            constraint=models.UniqueConstraint(fields=('moto', 'orden'), name='uq_seccionfichatecnica_moto_orden'),
        ),
        migrations.AddConstraint(
            model_name='itemfichatecnica',
            constraint=models.UniqueConstraint(fields=('seccion', 'orden'), name='uq_itemfichatecnica_seccion_orden'),
        ),
    ]
