# Generated by Django 6.0.3 on 2026-03-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0005_seccionfichatecnica_itemfichatecnica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('seccion', models.CharField(default='General', max_length=120)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['seccion', 'orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('seccion', 'nombre'), name='uq_tipoatributo_seccion_nombre')],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributoMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributos', to='motos.moto')),
                ('tipo_atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores_moto', to='motos.tipoatributo')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('moto', 'tipo_atributo'), name='uq_valoratributomoto_moto_tipoatributo')],
            },
        ),
    ]
