# Generated by Django 6.0.3 on 2026-03-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0006_tipoatributo_valoratributomoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoatributo',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='tipoatributo',
            name='uq_tipoatributo_seccion_nombre',
        ),
        migrations.RemoveConstraint(
            model_name='valoratributomoto',
            name='uq_valoratributomoto_moto_tipoatributo',
        ),
        migrations.AddField(
            model_name='valoratributomoto',
            name='nombre',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='tipoatributo',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_tipoatributo_nombre'),
        ),
        migrations.AddConstraint(
            model_name='valoratributomoto',
            constraint=models.UniqueConstraint(fields=('moto', 'tipo_atributo', 'nombre'), name='uq_valoratributomoto_moto_tipoatributo_nombre'),
        ),
        migrations.RemoveField(
            model_name='tipoatributo',
            name='seccion',
        ),
    ]
