# Generated by Django 6.0.3 on 2026-03-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0007_alter_tipoatributo_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tipoatributo',
            name='uq_tipoatributo_nombre',
        ),
    ]
