# Generated by Django 6.0.3 on 2026-03-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0008_remove_tipoatributo_uq_tipoatributo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='orden_carrusel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
