# Generated by Django 6.0.3 on 2026-03-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motos", "0009_moto_orden_carrusel"),
    ]

    operations = [
        migrations.AddField(
            model_name="moto",
            name="imagen_con_maletas",
            field=models.ImageField(blank=True, null=True, upload_to="motos/"),
        ),
        migrations.AddField(
            model_name="moto",
            name="permite_variante_maletas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="moto",
            name="precio_con_maletas",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
