# Generated by Django 6.0.3 on 2026-03-24 23:30

from django.db import migrations, models


def backfill_precio_lista(apps, schema_editor):
    Moto = apps.get_model("motos", "Moto")
    for moto in Moto.objects.all().only("id", "precio", "precio_lista"):
        if moto.precio_lista in (None, 0):
            moto.precio_lista = moto.precio
            moto.save(update_fields=["precio_lista"])


class Migration(migrations.Migration):

    dependencies = [
        ("motos", "0010_moto_variante_maletas"),
    ]

    operations = [
        migrations.AddField(
            model_name="moto",
            name="precio_lista",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="moto",
            name="precio_lista_con_maletas",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(backfill_precio_lista, migrations.RunPython.noop),
    ]
