# Generated by Codex on 2026-03-27
import django.db.models.deletion
from django.db import migrations, models


def cleanup_motos_integrity(apps, schema_editor):
    ModeloMoto = apps.get_model("motos", "ModeloMoto")
    Moto = apps.get_model("motos", "Moto")
    ValorAtributoMoto = apps.get_model("motos", "ValorAtributoMoto")
    ImagenMoto = apps.get_model("motos", "ImagenMoto")
    EspecificacionMoto = apps.get_model("motos", "EspecificacionMoto")

    for modelo in ModeloMoto.objects.all().only(
        "id",
        "cilindrada",
        "potencia",
        "torque",
        "peso",
        "capacidad_estanque",
    ):
        dirty = []
        if modelo.cilindrada is not None and modelo.cilindrada <= 0:
            modelo.cilindrada = None
            dirty.append("cilindrada")
        for field in ("potencia", "torque", "peso", "capacidad_estanque"):
            value = getattr(modelo, field)
            if value is not None and value < 0:
                setattr(modelo, field, 0)
                dirty.append(field)
        if dirty:
            modelo.save(update_fields=dirty)

    for moto in Moto.objects.all().only(
        "id",
        "marca_id",
        "modelo_moto_id",
        "precio",
        "precio_lista",
        "stock",
        "anio",
        "orden_carrusel",
        "permite_variante_maletas",
        "precio_con_maletas",
        "precio_lista_con_maletas",
    ):
        dirty = []
        if moto.modelo_moto_id:
            modelo_ref = ModeloMoto.objects.filter(id=moto.modelo_moto_id).only("marca_id").first()
            if modelo_ref and moto.marca_id != modelo_ref.marca_id:
                moto.marca_id = modelo_ref.marca_id
                dirty.append("marca")

        if moto.precio is not None and moto.precio < 0:
            moto.precio = 0
            dirty.append("precio")
        if moto.precio_lista is None or moto.precio_lista < 0:
            moto.precio_lista = 0
            dirty.append("precio_lista")
        if moto.precio is not None and moto.precio_lista is not None and moto.precio_lista < moto.precio:
            moto.precio_lista = moto.precio
            if "precio_lista" not in dirty:
                dirty.append("precio_lista")
        if moto.stock is not None and moto.stock < 0:
            moto.stock = 0
            dirty.append("stock")
        if moto.anio is None or moto.anio < 1990:
            moto.anio = 1990
            dirty.append("anio")
        elif moto.anio > 2100:
            moto.anio = 2100
            dirty.append("anio")
        if moto.orden_carrusel is None or moto.orden_carrusel < 1:
            moto.orden_carrusel = 1
            dirty.append("orden_carrusel")

        if not moto.permite_variante_maletas:
            if moto.precio_con_maletas is not None:
                moto.precio_con_maletas = None
                dirty.append("precio_con_maletas")
            if moto.precio_lista_con_maletas is not None:
                moto.precio_lista_con_maletas = None
                dirty.append("precio_lista_con_maletas")
        else:
            if moto.precio_con_maletas is None or moto.precio_con_maletas < 0:
                moto.precio_con_maletas = 0
                dirty.append("precio_con_maletas")
            if moto.precio_lista_con_maletas is None or moto.precio_lista_con_maletas < 0:
                moto.precio_lista_con_maletas = moto.precio_con_maletas
                dirty.append("precio_lista_con_maletas")
            if (
                moto.precio_lista_con_maletas is not None
                and moto.precio_con_maletas is not None
                and moto.precio_lista_con_maletas < moto.precio_con_maletas
            ):
                moto.precio_lista_con_maletas = moto.precio_con_maletas
                if "precio_lista_con_maletas" not in dirty:
                    dirty.append("precio_lista_con_maletas")

        if dirty:
            moto.save(update_fields=dirty)

    for item in ValorAtributoMoto.objects.all().only("id", "orden"):
        if item.orden is None or item.orden < 1:
            item.orden = 1
            item.save(update_fields=["orden"])

    for img in ImagenMoto.objects.all().only("id", "orden"):
        if img.orden is None or img.orden < 0:
            img.orden = 0
            img.save(update_fields=["orden"])

    seen = set()
    for spec in EspecificacionMoto.objects.all().only("id", "moto_id", "clave"):
        clave = (spec.clave or "").strip()
        if not clave:
            clave = f"clave-{spec.id}"
        base = clave
        i = 2
        key = (spec.moto_id, clave.lower())
        while key in seen:
            clave = f"{base}-{i}"
            key = (spec.moto_id, clave.lower())
            i += 1
        seen.add(key)
        if spec.clave != clave:
            spec.clave = clave
            spec.save(update_fields=["clave"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("catalogo", "0004_harden_integrity_catalog"),
        ("motos", "0017_valoratributomoto_tipo_control"),
    ]

    operations = [
        migrations.RunPython(cleanup_motos_integrity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="moto",
            name="marca",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="catalogo.marca"),
        ),
        migrations.AddIndex(
            model_name="moto",
            index=models.Index(
                fields=["activa", "es_destacada", "orden_carrusel", "id"],
                name="idx_moto_home_feed",
            ),
        ),
        migrations.AddIndex(
            model_name="moto",
            index=models.Index(
                fields=["marca", "modelo_moto", "activa"],
                name="idx_moto_marca_modelo_act",
            ),
        ),
        migrations.AddIndex(
            model_name="moto",
            index=models.Index(fields=["estado", "activa"], name="idx_moto_estado_activa"),
        ),
        migrations.AddConstraint(
            model_name="modelomoto",
            constraint=models.CheckConstraint(
                condition=models.Q(cilindrada__isnull=True) | models.Q(cilindrada__gt=0),
                name="chk_modelomoto_cilindrada_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelomoto",
            constraint=models.CheckConstraint(
                condition=models.Q(potencia__isnull=True) | models.Q(potencia__gte=0),
                name="chk_modelomoto_potencia_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelomoto",
            constraint=models.CheckConstraint(
                condition=models.Q(torque__isnull=True) | models.Q(torque__gte=0),
                name="chk_modelomoto_torque_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelomoto",
            constraint=models.CheckConstraint(
                condition=models.Q(peso__isnull=True) | models.Q(peso__gte=0),
                name="chk_modelomoto_peso_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelomoto",
            constraint=models.CheckConstraint(
                condition=models.Q(capacidad_estanque__isnull=True) | models.Q(capacidad_estanque__gte=0),
                name="chk_modelomoto_estanque_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(condition=models.Q(precio__gte=0), name="chk_moto_precio_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(condition=models.Q(precio_lista__gte=0), name="chk_moto_precio_lista_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(
                condition=models.Q(precio_lista__gte=models.F("precio")),
                name="chk_moto_lista_gte_precio",
            ),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(condition=models.Q(stock__gte=0), name="chk_moto_stock_gte_0"),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(
                condition=models.Q(anio__gte=1990) & models.Q(anio__lte=2100),
                name="chk_moto_anio_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(
                condition=models.Q(orden_carrusel__gte=1),
                name="chk_moto_orden_carrusel_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(
                condition=models.Q(permite_variante_maletas=False)
                | (models.Q(precio_con_maletas__isnull=False) & models.Q(precio_con_maletas__gte=0)),
                name="chk_moto_maletas_precio_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(
                condition=models.Q(permite_variante_maletas=False)
                | (
                    models.Q(precio_lista_con_maletas__isnull=False)
                    & models.Q(precio_lista_con_maletas__gte=0)
                ),
                name="chk_moto_maletas_lista_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="moto",
            constraint=models.CheckConstraint(
                condition=models.Q(precio_lista_con_maletas__isnull=True)
                | models.Q(precio_con_maletas__isnull=True)
                | models.Q(precio_lista_con_maletas__gte=models.F("precio_con_maletas")),
                name="chk_moto_lista_maletas_gte_precio",
            ),
        ),
        migrations.AddIndex(
            model_name="valoratributomoto",
            index=models.Index(
                fields=["moto", "tipo_atributo", "orden"],
                name="idx_valoratrib_moto_tipo_ord",
            ),
        ),
        migrations.AddConstraint(
            model_name="valoratributomoto",
            constraint=models.CheckConstraint(
                condition=models.Q(orden__gte=1),
                name="chk_valoratributo_orden_gte_1",
            ),
        ),
        migrations.AddIndex(
            model_name="imagenmoto",
            index=models.Index(fields=["moto", "orden"], name="idx_imagenmoto_moto_orden"),
        ),
        migrations.AddConstraint(
            model_name="imagenmoto",
            constraint=models.CheckConstraint(
                condition=models.Q(orden__gte=0),
                name="chk_imagenmoto_orden_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="especificacionmoto",
            constraint=models.UniqueConstraint(
                fields=["moto", "clave"],
                name="uq_especmoto_moto_clave",
            ),
        ),
        migrations.AddConstraint(
            model_name="especificacionmoto",
            constraint=models.CheckConstraint(
                condition=~models.Q(clave=""),
                name="chk_especmoto_clave_not_empty",
            ),
        ),
    ]
