# Generated by Codex on 2026-03-27
from django.db import migrations, models


def sync_moto_modelo_denormalized(apps, schema_editor):
    Moto = apps.get_model("motos", "Moto")
    ModeloMoto = apps.get_model("motos", "ModeloMoto")

    modelo_map = dict(ModeloMoto.objects.values_list("id", "nombre_modelo"))

    for moto in Moto.objects.all().only("id", "modelo", "modelo_moto_id"):
        expected = (modelo_map.get(moto.modelo_moto_id) or "").strip()
        if expected and moto.modelo != expected:
            moto.modelo = expected
            moto.save(update_fields=["modelo"])
        elif not expected:
            normalized = (moto.modelo or "").strip()
            if normalized != moto.modelo:
                moto.modelo = normalized
                moto.save(update_fields=["modelo"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("motos", "0018_harden_integrity_motos"),
    ]

    operations = [
        migrations.RunPython(sync_moto_modelo_denormalized, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="modelomoto",
            index=models.Index(fields=["activo", "marca", "nombre_modelo"], name="idx_modelomoto_act_marca_nom"),
        ),
        migrations.AddIndex(
            model_name="moto",
            index=models.Index(fields=["activa", "modelo"], name="idx_moto_activa_modelo"),
        ),
    ]
