# Generated by Django 6.0.3 on 2026-03-19 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha evento')),
                ('tipo_evento', models.CharField(choices=[('view_detail', 'Vista detalle'), ('view_list', 'Vista listado'), ('click', 'Click')], default='view_detail', max_length=24, verbose_name='tipo de evento')),
                ('tipo_entidad', models.CharField(choices=[('moto', 'Moto'), ('accesorio', 'Accesorio'), ('indumentaria', 'Indumentaria'), ('otro', 'Otro')], max_length=20, verbose_name='tipo entidad')),
                ('entidad_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id entidad')),
                ('entidad_slug', models.SlugField(blank=True, default='', max_length=180, verbose_name='slug entidad')),
                ('entidad_nombre', models.CharField(blank=True, default='', max_length=220, verbose_name='nombre entidad')),
                ('session_id', models.CharField(blank=True, default='', max_length=80, verbose_name='session id')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('origen', models.CharField(blank=True, default='', max_length=255, verbose_name='origen')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_catalogo', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evento de catalogo',
                'verbose_name_plural': 'eventos de catalogo',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['created_at'], name='idx_cat_event_created'), models.Index(fields=['tipo_entidad', 'created_at'], name='idx_cat_event_tipo_fecha'), models.Index(fields=['tipo_entidad', 'entidad_id'], name='idx_cat_event_tipo_entidad'), models.Index(fields=['session_id', 'created_at'], name='idx_cat_event_session_fecha'), models.Index(fields=['tipo_evento', 'created_at'], name='idx_cat_event_evento_fecha')],
            },
        ),
    ]
