# Generated by Codex on 2026-03-27
import django.db.models.deletion
from django.db import migrations, models


ACCESORIOS_SLUGS = {"accesorios-para-la-moto", "accesorios"}


def backfill_catalogo_integrity(apps, schema_editor):
    Marca = apps.get_model("catalogo", "Marca")
    CategoriaMoto = apps.get_model("catalogo", "CategoriaMoto")
    CategoriaProducto = apps.get_model("catalogo", "CategoriaProducto")
    SubcategoriaProducto = apps.get_model("catalogo", "SubcategoriaProducto")

    for marca in Marca.objects.all().only("id", "nombre", "tipo"):
        nombre = (marca.nombre or "").strip()
        if not nombre:
            marca.nombre = f"Marca {marca.id}"

        tipo = (marca.tipo or "").strip()
        if not tipo:
            has_moto = marca.modelos_moto.exists() or marca.moto_set.exists()
            if has_moto:
                marca.tipo = "moto"
            else:
                has_products = marca.productos.exists()
                has_acc_products = marca.productos.filter(subcategoria__categoria__slug__in=ACCESORIOS_SLUGS).exists()
                if has_acc_products:
                    marca.tipo = "accesorio_moto"
                elif has_products:
                    marca.tipo = "accesorio_rider"
                else:
                    marca.tipo = "moto"
        marca.save(update_fields=["nombre", "tipo"])

    for item in CategoriaMoto.objects.all().only("id", "nombre"):
        nombre = (item.nombre or "").strip()
        if not nombre:
            item.nombre = f"Categoria Moto {item.id}"
            item.save(update_fields=["nombre"])

    for item in CategoriaProducto.objects.all().only("id", "nombre"):
        nombre = (item.nombre or "").strip()
        if not nombre:
            item.nombre = f"Categoria Producto {item.id}"
            item.save(update_fields=["nombre"])

    for item in SubcategoriaProducto.objects.all().only("id", "nombre"):
        nombre = (item.nombre or "").strip()
        if not nombre:
            item.nombre = f"Subcategoria {item.id}"
            item.save(update_fields=["nombre"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("catalogo", "0003_backfill_marca_tipo"),
        ("motos", "0017_valoratributomoto_tipo_control"),
        ("productos", "0002_producto_orden_carrusel"),
    ]

    operations = [
        migrations.RunPython(backfill_catalogo_integrity, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="marca",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("moto", "Moto"),
                    ("accesorio_moto", "Accesorio moto"),
                    ("accesorio_rider", "Accesorio rider"),
                ],
                default="moto",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="subcategoriaproducto",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcategorias",
                to="catalogo.categoriaproducto",
            ),
        ),
        migrations.AddConstraint(
            model_name="marca",
            constraint=models.CheckConstraint(
                condition=~models.Q(nombre=""),
                name="chk_catalogo_marca_nombre_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="marca",
            constraint=models.CheckConstraint(
                condition=~models.Q(tipo=""),
                name="chk_catalogo_marca_tipo_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriamoto",
            constraint=models.CheckConstraint(
                condition=~models.Q(nombre=""),
                name="chk_catalogo_categoriamoto_nombre_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriaproducto",
            constraint=models.CheckConstraint(
                condition=~models.Q(nombre=""),
                name="chk_catalogo_categoriaprod_nombre_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategoriaproducto",
            constraint=models.CheckConstraint(
                condition=~models.Q(nombre=""),
                name="chk_catalogo_subcat_nombre_not_empty",
            ),
        ),
    ]
