# Generated by Codex on 2026-03-27
from django.db import migrations, models


def harden_marca_tipo(apps, schema_editor):
    Marca = apps.get_model("catalogo", "Marca")

    for marca in Marca.objects.all().only("id", "tipo"):
        tipo = (marca.tipo or "").strip()
        if tipo not in {"moto", "accesorio_moto", "accesorio_rider"}:
            marca.tipo = "moto"
            marca.save(update_fields=["tipo"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("catalogo", "0004_harden_integrity_catalog"),
    ]

    operations = [
        migrations.RunPython(harden_marca_tipo, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="marca",
            index=models.Index(fields=["activa", "tipo", "nombre"], name="idx_marca_activa_tipo_nom"),
        ),
        migrations.AddIndex(
            model_name="categoriaproducto",
            index=models.Index(fields=["activa", "nombre"], name="idx_catprod_activa_nombre"),
        ),
        migrations.AddIndex(
            model_name="subcategoriaproducto",
            index=models.Index(fields=["activa", "categoria", "nombre"], name="idx_subcat_act_cat_nom"),
        ),
    ]
