# Generated by Django 6.0.3 on 2026-03-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_split_nombre_completo_contactocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrador'), ('encargado', 'Encargado'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
