# Generated by Codex on 2026-03-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_alter_perfilusuario_rol"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="perfilusuario",
            index=models.Index(fields=["rol"], name="idx_perfilusuario_rol"),
        ),
        migrations.AddConstraint(
            model_name="perfilusuario",
            constraint=models.CheckConstraint(
                condition=~models.Q(rol=""),
                name="chk_perfilusuario_rol_not_empty",
            ),
        ),
        migrations.AlterModelOptions(
            name="contactocliente",
            options={"ordering": ["-fecha_creacion", "-id"]},
        ),
        migrations.AddIndex(
            model_name="contactocliente",
            index=models.Index(fields=["fecha_creacion"], name="idx_contactocliente_fecha"),
        ),
        migrations.AddIndex(
            model_name="contactocliente",
            index=models.Index(fields=["moto"], name="idx_contactocliente_moto"),
        ),
        migrations.AddIndex(
            model_name="contactocliente",
            index=models.Index(fields=["producto"], name="idx_contactocliente_producto"),
        ),
        migrations.AddConstraint(
            model_name="contactocliente",
            constraint=models.CheckConstraint(
                condition=~models.Q(nombres=""),
                name="chk_contactocliente_nombres_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactocliente",
            constraint=models.CheckConstraint(
                condition=~models.Q(apellidos=""),
                name="chk_contactocliente_apellidos_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactocliente",
            constraint=models.CheckConstraint(
                condition=~models.Q(telefono=""),
                name="chk_contactocliente_telefono_not_empty",
            ),
        ),
    ]
