import {
  createCategoriaMoto,
  createMarca,
  createMoto,
  deleteMoto,
  deleteCategoriaMoto,
  deleteMarca,
  deleteModeloMoto,
  getCategoriasMoto,
  getMarcasAdmin,
  getMotoAdminMeta,
  getModelosMoto,
  getMotos,
  updateMoto,
  updateCategoriaMoto,
  updateMarca,
  updateModeloMoto,
  createModeloMoto,
} from "../../../services/motosService";

export {
  createCategoriaMoto,
  createMarca,
  createMoto,
  deleteMoto,
  deleteCategoriaMoto,
  deleteMarca,
  deleteModeloMoto,
  getCategoriasMoto,
  getMarcasAdmin,
  getMotoAdminMeta,
  getModelosMoto,
  getMotos,
  updateMoto,
  updateCategoriaMoto,
  updateMarca,
  updateModeloMoto,
  createModeloMoto,
};
