import { useMemo } from "react";

export default function useAdminSectionProps({ activeSection, loading, dashboard, activeMarcaConfig, domains }) {
  return useMemo(() => {
    const { motos, productos, users, configuracion, mantenciones, horarios, entityActions } = domains;

    return {
      resumen: {
        loading,
        dashboard,
        marcasMotosAdmin: motos.marcasMotosAdmin,
        marcasAccRiderAdmin: productos.marcasAccRiderAdmin,
        marcasAccMotosAdmin: productos.marcasAccMotosAdmin,
      },
      motos: {
        activeSection,
        loading,
        dashboard,
        activeMarcaConfig,
        marcasMotosAdmin: motos.marcasMotosAdmin,
        marcasAccMotosAdmin: productos.marcasAccMotosAdmin,
        marcasAccRiderAdmin: productos.marcasAccRiderAdmin,
        marcaForm: motos.marcaForm,
        marcaSaving: motos.marcaSaving,
        onMarcaInputChange: motos.handleMarcaInputChange,
        onMarcaSubmit: motos.handleMarcaSubmit,
        onMarcaEdit: entityActions.handleMarcaEdit,
        onMarcaDelete: entityActions.handleMarcaDelete,
        modelosMotosAdmin: motos.modelosMotosAdmin,
        modeloMotoForm: motos.modeloMotoForm,
        modeloMotoSaving: motos.modeloMotoSaving,
        onModeloMotoInputChange: motos.handleModeloMotoInputChange,
        onModeloMotoSubmit: motos.handleModeloMotoSubmit,
        onModeloMotoEdit: entityActions.handleModeloMotoEdit,
        onModeloMotoDelete: entityActions.handleModeloMotoDelete,
        motoForm: motos.motoForm,
        motoSaving: motos.motoSaving,
        motoMeta: motos.motoMeta,
        motoImageInputKey: motos.motoImageInputKey,
        onMotoInputChange: motos.handleMotoInputChange,
        onMotoPrecioInputChange: motos.handleMotoPrecioInputChange,
        onMotoPrecioListaInputChange: motos.handleMotoPrecioListaInputChange,
        onMotoPrecioConMaletasInputChange: motos.handleMotoPrecioConMaletasInputChange,
        onMotoPrecioListaConMaletasInputChange: motos.handleMotoPrecioListaConMaletasInputChange,
        onMotoSubmit: motos.handleMotoSubmit,
        onMotoEdit: motos.handleMotoEdit,
        onMotoDelete: motos.handleMotoDelete,
        motoDeleteModal: motos.motoDeleteModal,
        motoDeleteSaving: motos.motoDeleteSaving,
        onCloseMotoDeleteModal: motos.closeMotoDeleteModal,
        onConfirmMotoDelete: motos.submitMotoDelete,
        categoriasMoto: motos.categoriasMoto,
        categoriaMotoForm: motos.categoriaMotoForm,
        categoriaMotoSaving: motos.categoriaMotoSaving,
        onCategoriaMotoInputChange: motos.handleCategoriaMotoInputChange,
        onCategoriaMotoSubmit: motos.handleCategoriaMotoSubmit,
        onCategoriaMotoEdit: entityActions.handleCategoriaMotoEdit,
        onCategoriaMotoDelete: entityActions.handleCategoriaMotoDelete,
        accesoriosMotosMeta: productos.accesoriosMotosMeta,
      },
      fichas: {
        activeSection,
        motos: dashboard.motos,
      },
      productos: {
        activeSection,
        loading,
        categoriasAccMotosMeta: productos.categoriasAccMotosMeta,
        categoriaAccMotosForm: productos.categoriaAccMotosForm,
        categoriaAccMotosSaving: productos.categoriaAccMotosSaving,
        onCategoriaAccMotosInputChange: productos.handleCategoriaAccMotosInputChange,
        onCategoriaAccMotosSubmit: productos.handleCategoriaAccMotosSubmit,
        onCategoriaAccMotosEdit: entityActions.handleCategoriaAccMotosEdit,
        onCategoriaAccMotosDelete: entityActions.handleCategoriaAccMotosDelete,
        categoriasAccRiderMeta: productos.categoriasAccRiderMeta,
        categoriaAccRiderForm: productos.categoriaAccRiderForm,
        categoriaAccRiderSaving: productos.categoriaAccRiderSaving,
        onCategoriaAccRiderInputChange: productos.handleCategoriaAccRiderInputChange,
        onCategoriaAccRiderSubmit: productos.handleCategoriaAccRiderSubmit,
        onCategoriaAccRiderEdit: entityActions.handleCategoriaAccRiderEdit,
        onCategoriaAccRiderDelete: entityActions.handleCategoriaAccRiderDelete,
        accesoriosMotosMeta: productos.accesoriosMotosMeta,
        accesoriosMotosAdmin: productos.accesoriosMotosAdmin,
        accesorioMotoForm: productos.accesorioMotoForm,
        accesorioMotoImageInputKey: productos.accesorioMotoImageInputKey,
        accesorioMotoImageUrl: productos.accesorioMotoImageUrl,
        accesorioMotoSaving: productos.accesorioMotoSaving,
        editingAccesorioMotoId: productos.editingAccesorioMotoId,
        onAccesorioMotoInputChange: productos.handleAccesorioMotoInputChange,
        onAccesorioMotoPrecioInputChange: productos.handleAccesorioMotoPrecioInputChange,
        onAccesorioMotoSubmit: productos.handleAccesorioMotoSubmit,
        onAccesorioMotoEdit: productos.handleAccesorioMotoEdit,
        onAccesorioMotoDelete: productos.handleAccesorioMotoDelete,
        productoDeleteModal: productos.productoDeleteModal,
        productoDeleteSaving: productos.productoDeleteSaving,
        onCloseProductoDeleteModal: productos.closeProductoDeleteModal,
        onConfirmProductoDelete: productos.submitProductoDelete,
        onCancelAccesorioMotoEdit: productos.handleCancelAccesorioMotoEdit,
        onToggleCompatibilidad: productos.toggleAccesorioCompatibilidadMoto,
        motoMeta: motos.motoMeta,
        accesoriosRiderMeta: productos.accesoriosRiderMeta,
        accesoriosRiderAdmin: productos.accesoriosRiderAdmin,
        accesorioRiderForm: productos.accesorioRiderForm,
        accesorioRiderImageInputKey: productos.accesorioRiderImageInputKey,
        accesorioRiderImageUrl: productos.accesorioRiderImageUrl,
        accesorioRiderSaving: productos.accesorioRiderSaving,
        onAccesorioRiderInputChange: productos.handleAccesorioRiderInputChange,
        onAccesorioRiderPrecioInputChange: productos.handleAccesorioRiderPrecioInputChange,
        onAccesorioRiderSubmit: productos.handleAccesorioRiderSubmit,
        onAccesorioRiderEdit: productos.handleAccesorioRiderEdit,
        onAccesorioRiderDelete: productos.handleAccesorioRiderDelete,
      },
      configuracion: {
        activeSection,
        contactoForm: configuracion.contactoForm,
        contactoSaving: configuracion.contactoSaving,
        contactoLoading: configuracion.contactoLoading,
        contactoLoadError: configuracion.contactoLoadError,
        onContactoInputChange: configuracion.handleContactoInputChange,
        onContactoSubmit: configuracion.handleContactoSubmit,
        onContactoRetry: configuracion.reloadContacto,
      },
      mantenciones: {
        activeSection,
        loading: mantenciones.mantencionesLoading,
        mantencionesLoadError: mantenciones.mantencionesLoadError,
        mantenciones: mantenciones.mantenciones,
        savingById: mantenciones.mantencionSavingById,
        onAcceptSolicitud: mantenciones.handleAcceptMantencionSolicitud,
        onUpdateMantencion: mantenciones.handleUpdateMantencion,
        horarios: horarios.horariosMantencion,
        horariosLoading: horarios.horariosMantencionLoading,
        horariosLoadError: horarios.horariosLoadError,
        horarioForm: horarios.horarioMantencionForm,
        horarioSaving: horarios.horarioMantencionSaving,
        onHorarioInputChange: horarios.handleHorarioMantencionInputChange,
        onHorarioSubmit: horarios.handleHorarioMantencionSubmit,
        onHorarioUpdate: horarios.handleUpdateHorarioMantencion,
        onHorarioDelete: horarios.handleDeleteHorarioMantencion,
      },
      usuarios: {
        activeSection,
        createUserForm: users.createUserForm,
        createUserSaving: users.createUserSaving,
        onCreateUserInputChange: users.handleCreateUserInputChange,
        onCreateUserSubmit: users.handleCreateUserSubmit,
        adminUsers: users.adminUsers,
        adminUsersLoading: users.adminUsersLoading,
        adminUsersLoadError: users.adminUsersLoadError,
        paginatedAdminUsers: users.paginatedAdminUsers,
        onEditUser: users.openAdminUserEditModal,
        onDeleteUser: users.openAdminUserDeleteModal,
        onPageChange: users.setAdminUsersPage,
      },
    };
  }, [activeSection, activeMarcaConfig, dashboard, domains, loading]);
}
