# Generated by Django 6.0.3 on 2026-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden_carrusel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
