# Generated by Codex on 2026-03-27
from collections import defaultdict

from django.db import migrations, models
from django.db.models.functions import Lower


def cleanup_productos_integrity(apps, schema_editor):
    Producto = apps.get_model("productos", "Producto")
    ImagenProducto = apps.get_model("productos", "ImagenProducto")
    EspecificacionProducto = apps.get_model("productos", "EspecificacionProducto")

    for producto in Producto.objects.all().only("id", "nombre", "precio", "stock", "orden_carrusel"):
        dirty = []
        nombre = (producto.nombre or "").strip()
        if not nombre:
            producto.nombre = f"Producto {producto.id}"
            dirty.append("nombre")
        if producto.precio is None or producto.precio < 0:
            producto.precio = 0
            dirty.append("precio")
        if producto.stock is None or producto.stock < 0:
            producto.stock = 0
            dirty.append("stock")
        if producto.orden_carrusel is None or producto.orden_carrusel < 1:
            producto.orden_carrusel = 1
            dirty.append("orden_carrusel")
        if dirty:
            producto.save(update_fields=dirty)

    # Dedupe semantico por (subcategoria, marca, lower(nombre)).
    buckets = defaultdict(list)
    for item in Producto.objects.all().only("id", "nombre", "subcategoria_id", "marca_id"):
        key = (item.subcategoria_id, item.marca_id, (item.nombre or "").strip().lower())
        buckets[key].append(item.id)
    for (_subcat, _marca, _name), ids in buckets.items():
        if len(ids) <= 1:
            continue
        ids_sorted = sorted(ids)
        for dup_id in ids_sorted[1:]:
            prod = Producto.objects.only("id", "nombre").get(id=dup_id)
            base = (prod.nombre or "").strip() or f"Producto {prod.id}"
            prod.nombre = f"{base} ({prod.id})"
            prod.save(update_fields=["nombre"])

    for image in ImagenProducto.objects.all().only("id", "orden"):
        if image.orden is None or image.orden < 0:
            image.orden = 0
            image.save(update_fields=["orden"])

    seen = set()
    for spec in EspecificacionProducto.objects.all().only("id", "producto_id", "clave"):
        clave = (spec.clave or "").strip()
        if not clave:
            clave = f"clave-{spec.id}"
        base = clave
        i = 2
        key = (spec.producto_id, clave.lower())
        while key in seen:
            clave = f"{base}-{i}"
            key = (spec.producto_id, clave.lower())
            i += 1
        seen.add(key)
        if spec.clave != clave:
            spec.clave = clave
            spec.save(update_fields=["clave"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("productos", "0002_producto_orden_carrusel"),
    ]

    operations = [
        migrations.RunPython(cleanup_productos_integrity, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["activo", "subcategoria", "marca"],
                name="idx_producto_act_sub_marca",
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["es_destacado", "orden_carrusel", "id"],
                name="idx_producto_destacado_ord",
            ),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["precio"], name="idx_producto_precio"),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(precio__gte=0),
                name="chk_producto_precio_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(stock__gte=0),
                name="chk_producto_stock_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.CheckConstraint(
                condition=models.Q(orden_carrusel__gte=1),
                name="chk_producto_orden_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                Lower("nombre"),
                "subcategoria",
                "marca",
                condition=models.Q(marca__isnull=False),
                name="uq_producto_semantic_marca",
            ),
        ),
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                Lower("nombre"),
                "subcategoria",
                condition=models.Q(marca__isnull=True),
                name="uq_producto_semantic_nomarca",
            ),
        ),
        migrations.AddIndex(
            model_name="imagenproducto",
            index=models.Index(
                fields=["producto", "orden"],
                name="idx_imagenprod_prod_orden",
            ),
        ),
        migrations.AddConstraint(
            model_name="imagenproducto",
            constraint=models.CheckConstraint(
                condition=models.Q(orden__gte=0),
                name="chk_imagenprod_orden_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="especificacionproducto",
            constraint=models.UniqueConstraint(
                fields=["producto", "clave"],
                name="uq_especprod_producto_clave",
            ),
        ),
        migrations.AddConstraint(
            model_name="especificacionproducto",
            constraint=models.CheckConstraint(
                condition=~models.Q(clave=""),
                name="chk_especprod_clave_not_empty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="compatibilidadproductomoto",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="compatibilidadproductomoto",
            constraint=models.UniqueConstraint(
                fields=["producto", "moto"],
                name="uq_compat_producto_moto",
            ),
        ),
        migrations.AddIndex(
            model_name="compatibilidadproductomoto",
            index=models.Index(
                fields=["moto", "producto"],
                name="idx_compat_moto_producto",
            ),
        ),
        migrations.AddIndex(
            model_name="compatibilidadproductomoto",
            index=models.Index(fields=["producto"], name="idx_compat_producto"),
        ),
    ]
