# Generated by Django 6.0.3 on 2026-03-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('ubicacion', models.CharField(blank=True, max_length=180)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto del sitio',
                'verbose_name_plural': 'Contacto del sitio',
            },
        ),
    ]
