# Generated by Codex on 2026-03-27
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.CharField(db_index=True, max_length=64)),
                ("entidad", models.CharField(db_index=True, max_length=120)),
                ("entidad_id", models.CharField(db_index=True, max_length=64)),
                (
                    "accion",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["entidad", "entidad_id", "-creado_en"], name="idx_audit_entidad_fecha"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor", "-creado_en"], name="idx_audit_actor_fecha"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["accion", "-creado_en"], name="idx_audit_accion_fecha"),
        ),
    ]
